language: node_js
node_js: 14.3
cache: npm
os: linux
dist: xenial
services:
  - docker

script:
  - npm run lint
  - npm run test:server

deploy:
  provider: script
  script: bash deployment/build-images.sh
  on:
    condition: $TRAVIS_BRANCH = "master" || $TRAVIS_PULL_REQUEST = "true"
