language: node_js
node_js: 14.3
cache: npm
sudo: required
services:
  - docker

script:
  - npm run lint
  - npm run test:server

deploy:
  provider: script
  script: ./deployment/build-images.sh
  on:
    condition: (type = pull_request) OR (branch = master)
