language: node_js
node_js:
  - 14.3.0
  - 14.3
  - 14
cache: npm
sudo: required
services:
  - docker

before_script:
  - npm ci

jobs:
  include:
    - stage: Linting
      script:
        - npm run lint
    - stage: Tests
      script:
        - npm run test:server
    - stage: Docker image dry build
      if: type = pull_request
      script:
        - docker build . -t $DOCKER_IMAGE_NAME:$TRAVIS_BUILD_NUMBER
    - stage: Docker image deploy
      if: branch = master
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build . -t $DOCKER_USER/$DOCKER_IMAGE_NAME:latest
        - docker push $DOCKER_USER/$DOCKER_IMAGE_NAME:latest
